SQLALCHEMY_DATABASE_URI = 'db_protocol://user:pass@host:port/database'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'secret_key'
SECURITY_REGISTERABLE = True
SECURITY_PASSWORD_HASH = 'bcrypt'
SECURITY_PASSWORD_SALT = 'password_salt'
DEBUG = True

UPLOAD_FOLDER = '/uploads/'
TEMP_FOLDER = '/tmp/'
ALLOWED_EXTENSIONS = set(['pdf', 'PDF', 'png', 'PNG'])
DOWNLOAD_PROTOCOL = 'http'
DOWNLOAD_DOMAIN = 'www.coalman.io'

MAIL_SERVER = ''
MAIL_PORT = 587
MAIL_USE_SSL = True
MAIL_USERNAME = ''
MAIL_PASSWORD = ''